# Generated by Django 4.0 on 2022-01-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category name *')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='*')),
            ],
        ),
    ]
