# Generated by Django 4.0.2 on 2022-02-12 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(default=datetime.datetime(2022, 2, 12, 16, 34, 45, 283268, tzinfo=utc), verbose_name='*'),
            preserve_default=False,
        ),
    ]
