# Generated by Django 4.0 on 2022-01-28 04:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='product nomi'),
        ),
    ]
