# Generated by Django 4.0.2 on 2022-02-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Total',
            new_name='total',
        ),
    ]
