# Generated by Django 4.0.2 on 2022-02-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_total_order_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
