# Generated by Django 4.0 on 2022-01-28 04:28

import ckeditor.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2022, 1, 28, 4, 28, 9, 426757, tzinfo=utc), verbose_name='product nomi'),
            preserve_default=False,
        ),
    ]
